<?php

/**
 * @author Luis Sanchez <luis.sanchez.saldana@gmail.com>
 */

namespace Stiwl\PageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository {

    public function findAllToSonataAdmin_query_language($query, $language) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $query->addSelect('languages')
                ->join('o.languages', 'languages')
                ->where($qb->expr()->eq('languages.language', ':language'))
                ->setParameter('language', $language)
        ;
        return $query;
    }

    public function findAll_language($language) {
        $qb = $this->createQueryBuilder('category');
        $qb->addSelect('languages')
                ->join('category.languages', 'languages')
                ->where($qb->expr()->eq('languages.language', ':language'))
                ->andWhere($qb->expr()->eq('category.status', ':status'))
                ->setParameter('language', $language)
                ->setParameter('status', '1')
        ;
        $query = $qb->getQuery();
        return $query->getResult();
    }

    public function findOne_id_language($id, $language) {
        $qb = $this->createQueryBuilder('category');
        $qb->addSelect('languages')
                ->join('category.languages', 'languages')
                ->where('languages.language = :language')
                ->andWhere('category.id = :id')
                ->setParameter('language', $language)
                ->setParameter('id', $id)
        ;
        $query = $qb->getQuery();
        return $query->getOneOrNullResult();
    }

}
